### ISSUE TITLE
This example now fails to build with "error: failed to run custom build command for `ocaml-boxroot-sys v0.2.0`"

### ISSUE THREAD

**Issue by emchristiansen** [zshipko/rust-ocaml-starter#3]
I think something in the dependency chain just broke - this example now fails to build with:

```
error: failed to run custom build command for `ocaml-boxroot-sys v0.2.0`
```

I believe it was working 2 days ago.

**Comment by zshipko** [comment]
Thanks! This is probably due to the new boxroot release, I will take a look.

**Comment by zshipko** [comment]
It looks like this is because you're using an OCaml 5 switch - you would need to used the `ocaml5` branch of ocaml-rs until it gets merged.

**Comment by emchristiansen** [comment]
Perhaps you're right - I have a 4.14.1 switch in my example directory, but maybe I forgot to `eval` it.
In any case, this seems to work now - sorry for the false alarm.
